name: BungeecordMOTDServerCount
version: @plugin.version@
author: JacksonChen666
main: com.jacksonchen666.bungeecordmotdservercount.BungeecordMOTDServerCount
api-version: 1.16

commands:
  serversonline:
    description: Gets how many servers are online.
    permission: BungeecordMOTDServerCount.user

permissions:
  BungeecordMOTDServerCount.user:
    default: true
    description: Joe's permission.
  BungeecordMOTDServerCount.admin:
    default: op
    description: Admin's permisison.
    children:
      BungeecordMOTDServerCount.reload: true
  BungeecordMOTDServerCount.reload:
    description: Reload plugin config permission.